config/routes.rb
Rails.application.routes.draw do
  get 'yoti' => 'yoti#index',  as: 'yoti'
  get 'callback/yoti', to: 'yoti#profile'
  devise_for :users
  resources :store
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if current_user.yoti_id.nil?
      yoti_path
    else
      root_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_filter :authenticate_user!
  before_filter do
    redirect_to yoti_path unless current_user && !current_user.yoti_id.nil?
  end



end

app/controllers/yoti_controller.rb
class YotiController < ApplicationController
  before_action :authenticate_user!
  # before_filter  only: :profile do
  #   redirect_to yoti_path unless current_user && !current_user.yoti_id.nil?
  # end

  def index
    @yoti_application_id = ENV['YOTI_APPLICATION_ID']
  end

  def profile
    yoti_activity_details = Yoti::Client.get_activity_details(params[:token])
    if yoti_activity_details.outcome == 'SUCCESS'
      current_user.update_attributes yoti_id: yoti_activity_details.user_id
      @user_id = yoti_activity_details.user_id

      user_profile = yoti_activity_details.user_profile
      @photo = user_profile['selfie']
      @given_names = user_profile['given_names']
      @family_name = user_profile['family_name']
      @mobile_number = user_profile['phone_number']
      @date_of_birth = user_profile['date_of_birth']
      @address = user_profile['post_code']
      @gender = user_profile['gender']
      @nationality = user_profile['nationality']
    else
      render text: 'Error: Fetching the activity details failed.', status: :error
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/yoti_helper.rb
module YotiHelper
end

app/views/layouts/application.html.slim
doctype html
html[lang="en-US"]
  head
    meta[charset="UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title
      | Brewhouse | Buy beer online

    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    link#brewhouse-font-awesome-css[rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css?ver=4.7.0" type="text/css" media="all"]
    link#brewhouse-francois-css[rel="stylesheet" href="//fonts.googleapis.com/css?family=Francois+One&#038;ver=5999f1ec59ceb14f800c309a6ccf1b50" type="text/css" media="all"]
    link#brewhouse-source-sans-css[rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro%3A400%2C300%2C600italic%2C600%2C900&#038;ver=5999f1ec59ceb14f800c309a6ccf1b50" type="text/css" media="all"]

    link#googleFonts-css[rel="stylesheet" href="//fonts.googleapis.com/css?family=Francois+One%7CSource+Sans+Pro%3A400%2C300%2C600italic%2C600%2C900&#038;ver=5999f1ec59ceb14f800c309a6ccf1b50" type="text/css" media="all"]
    link[href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"]
    style[type="text/css"]
      | .recentcomments a{display:inline !important;padding:0 !important;margin:0 !important;}
  body#skrollr-body

    #page.hfeed.site

          a.skip-link.screen-reader-text[href="#content"]
            | Skip to content
          header#masthead.site-header[role="banner"]
            .grid.grid-pad
              .site-branding.col-9-12.mobile-col-8-12
                .site-logo
                  a[href="#" title="Brewhouse" rel="home"]
                    img[src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/brewhouse.png" alt="Brewhouse"]
              .col-3-12.mobile-col-4-12.push-right
                button.toggle-menu.menu-right.push-right
                  span.hide-on-mobile
                    | Menu
                  i.fa.fa-bars
          nav.cbp-spmenu.cbp-spmenu-vertical.cbp-spmenu-right
            h3
              | Menu
            .menu-menu-1-container
              ul#menu-menu-1.menu
                li#menu-item-152.menu-item.menu-item-type-post_type.menu-item-object-page.current-menu-item.page_item.page-item-142.current_page_item.menu-item-152
                  = link_to 'Home', root_path
                li#menu-item-159.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-has-children.menu-item-159
                   = link_to 'Store', store_index_path
                li#menu-item-146.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-146
                  - if user_signed_in?
                    = link_to "Sign out", destroy_user_session_path, :method => :delete
                  - else
                    = link_to 'Sign in', new_user_session_path
                li#menu-item-158.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-158
                   = link_to 'Sign up', new_user_registration_path
            a.toggle-menu.menu-right.close-btn
              i.fa.fa-remove.push-right[style="margin-top: 12px;"]
    h3.text-center.alert
      - if notice || alert
        br
        br
        p.notice
          = notice
        p.alert
          = alert

    = yield

    footer#colophon.site-footer[role="contentinfo"]
      .grid.grid-pad
        .footer-block.col-1-3
          .footer-block-text
            i.fa.fa-mobile
            h5
              | 555-555-BREW
              br
              |  contact@brewhouse.com
        .footer-block.col-1-3
          .footer-block-text
            i.fa.fa-map-marker
            h5
              | 100 Brew St. New York, NY
              br
              |  Hours: M-F: 10-7 | Sat: 11-8
        .footer-block.col-1-3
          .footer-block-text
            i.fa.fa-comments-o
            ul.social-media-icons
              li
                a[href="https://twitter.com"]
                  i.fa.fa-twitter
              li
                a[href="https://facebook.com"]
                  i.fa.fa-facebook
              li
                a[href="https://pinterest.com"]
                  i.fa.fa-pinterest
              li
                a[href="https://tumblr.com"]
                  i.fa.fa-tumblr
      .grid.grid-pad
    .border--top
    .border--right
    .border--bottom
    .border--left
    javascript:
      $(function() {
        window.scrollTo(0,0);
        setTimeout(function(){
          $('.alert').slideUp(500);
        }, 2000);
      });

app/views/pages/home.html.slim
section#content.site-content
  #slides
    .slides-container
      #scene.slide-content
        .box-align
          .vertical-align
            .layer.data[data-depth="0.20"]
              img.badge.preserve.hide-on-mobile[src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/08/badge.png" alt="Brewhouse"]
            .layer.data[data-depth="0.40"]
              h2
                | Scroll or Tilt.
                br
                | Optional Tipsy Effect.
            .layer.data[data-depth="0.65"]
              a[href="#jump-to"]
                i.fa.fa-angle-down
        img.layer.home-background[data-depth="0.10" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/08/parallax-bg.jpg" alt="Brewhouse"]
  #jump-to.home-info
    .color-dark
      .color-text
        i.fa.fa-home
        h2
          | Login
        aside#text-3.widget.widget_text
          .textwidget
            p
              | Login to your account here
        =link_to new_user_session_path do
          button
            | Login
    .color-light
      .color-text
        i.fa.fa-thumbs-o-up
        h2
          | Register
          br
          | You must be over 18
        aside#text-4.widget.widget_text
          .textwidget
            p
              | We use Yoti to verify that you're over 18 to buy alcohol!
        =link_to new_user_session_path do
          button
            | Register here
  #cta-parallax.home-cta
    #scene2.cta-content
      .layer[data-depth="0.20"]
        h2
          | Specialty Beers.
        hr.hr
      .layer[data-depth="0.40"]
        aside#text-5.widget.widget_text
          .textwidget
            p
              | Buy beers in our online store!
      .layer[data-depth="0.65"]
        = link_to store_index_path do
          button.white-btn
            | View Full Menu
    #scene-bg
      img.layer.cta-parallax-bg[src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/cta-bg.jpg" data-depth="0.10" alt="Brewhouse"]
  .featured-drinks
    .grid.grid-pad
      .col-1-4
        .featured-drink
          img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer1.png" alt="beer1"]
          span
            | Modern Ale
          em
            | 26 IBU / 5.4%
          p
            | Brewed with locally grown hops and a handful of love.
      .col-1-4
        .featured-drink
          img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer2.png" alt="beer2"]
          span
            | Illegally Blonde
          em
            | 43 IBU / 4.7%
          p
            | Brewed with locally grown hops and a handful of love.
      .col-1-4
        .featured-drink
          img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer3.png" alt="beer3"]
          span
            | Whitecaps Witte
          em
            | 43 IBU / 4.7%
          p
            | Brewed with locally grown hops and a handful of love.
      .col-1-4
        .featured-drink
          img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer1.png" alt="beer1"]
          span
            | Le Bat Bleu
          em
            | 43 IBU / 4.7%
          p
            | Brewed with locally grown hops and a handful of love.

app/views/store/index.html.slim
section#content.site-content
  #primary.content-area
    main#main.site-main[role="main"]
      header.entry-header
        #scene
          img.layer.page-header[data-depth="0.10" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/08/page-bg2.jpg" alt="Brewhouse"]
          .page-entry-header
            .layer.data[data-depth="0.40"]
              h2
              h1.page-entry-title
                | Our Beer List
            .layer.data[data-depth="0.80"]
              a[href="#jump-to"]
                i.fa.fa-angle-down
      #jump-to.entry-content
        .beer-list
          .grid.grid-pad
            .col-1-1
              h2.underline
                span
                  | Currently Available
          .grid.grid-pad
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer1.png" alt="beer1"]
                span
                  | Modern Ale
                em
                  | 26 IBU / 5.4%
                p
                  | Brewed with locally grown hops and a handful of love.
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer2.png" alt="beer2"]
                span
                  | Illegally Blonde
                em
                  | 43 IBU / 4.7%
                p
                  | Brewed with locally grown hops and a handful of love.
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer3.png" alt="beer3"]
                span
                  | Whitecaps Witte
                em
                  | 43 IBU / 4.7%
                p
                  | Brewed with locally grown hops and a handful of love.
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer1.png" alt="beer1"]
                span
                  | Le Bat Bleu
                em
                  | 43 IBU / 4.7%
                p
                  | Brewed with locally grown hops and a handful of love.
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer3.png" alt="beer3"]
                span
                  | Top of the Froth
                em
                  | 43 IBU / 4.7%
                p
                  | Brewed with locally grown hops and a handful of love.
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer1.png" alt="beer1"]
                span
                  | Eye Pea Eh?
                em
                  | 43 IBU / 4.7%
                p
                  | Brewed with locally grown hops and a handful of love.
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/09/beer2.png" alt="beer2"]
                span
                  | Almost Red Ale
                em
                  | 26 IBU / 5.4%
                p
                  | Brewed with locally grown hops and a handful of love.
            .col-1-4
              .featured-drink
                img.beer.wp-post-image[width="138" height="200" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/08/beer1.png" alt="beer1"]
                span
                  | Tasty Treat
                em
                  | 43 IBU / 4.7%
                p
                  | Brewed with locally grown hops and a handful of love.
      footer.col-1-1.entry-footer

  .home-info
    .color-light
      .color-text
        i.fa
        h2
          | Footer
          br
          | Widget Area
        aside#text-6.widget.widget_text
          .textwidget
            p
              | Use this area to display anything from simple text, to your latest blog posts, or even a newsletter sign-up!
        a[href="#"]
          button
            | More About Us
    .color-dark
      .color-text
        i.fa.fa-envelope-o
        h2
          | Contact us
          br
          | Today!
        aside#text-7.widget.widget_text
          .textwidget
            p
              | Want to plan your next party or event at brew house? Contact us today and get the party started.
        a[href="#"]
          button
            | Contact us
            br
            | Today!

app/views/yoti/index.html.slim
section#content.site-content
#primary.content-area
  main#main.site-main[role="main"]
    header.entry-header
      #scene
        img.layer.page-header[data-depth="0.10" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/08/page-bg2.jpg" alt="Brewhouse"]
        .page-entry-header
          .layer.data[data-depth="0.40"]
            h2
            h1.page-entry-title
              | Over 18?
          .layer.data[data-depth="0.80"]
            a[href="#jump-to"]
              i.fa.fa-angle-down
    #jump-to.entry-content
      .beer-list
        .grid.grid-pad
          .col-1-1.text-center
            h2 You must be over 18 to access our store!
            br
            <a class="btn button yoti-connect learn-more btn-primary" data-target='embed' data-yoti-application-id="#{@yoti_application_id}">Sign up with Yoti</a>
            br
<script src="https://sdk.yoti.com/clients/browser.js"></script>
  javascript:
      _ybg.config.service = 'https://code.yoti.com/app/'
      _ybg.init()
br
br

app/views/yoti/profile.html.slim
section#content.site-content
#primary.content-area
  main#main.site-main[role="main"]
    header.entry-header
      #scene
        img.layer.page-header[data-depth="0.10" src="https://modernthemes.net/wordpress-demo/brewhouse/wp-content/uploads/sites/6/2014/08/page-bg2.jpg" alt="Brewhouse"]
        .page-entry-header
          .layer.data[data-depth="0.40"]
            h2
            h1.page-entry-title
              | "Thankyou!"
          .layer.data[data-depth="0.80"]
            a[href="#jump-to"]
              i.fa.fa-angle-down
    #jump-to.entry-content
      .beer-list
        .grid.grid-pad
          .col-1-1.text-center
            h2 = link_to "You can now visit the store!", store_index_path
            br
            br
            = "user_id = #{@user_id}"